SELECT CONCAT('UPDATE `databases` SET `accepted_species_names` = ',
 `accepted_species_names`,
 ', `accepted_infraspecies_names` = ',
 `accepted_infraspecies_names`,
 ', `species_synonyms` = ',
 `species_synonyms`,
 ', `infraspecies_synonyms` =',
 `infraspecies_synonyms`,
 ', `common_names` = ',
 `common_names`,
 ', `total_names` = ',
 `total_names`,
 ', `is_new` =',
 2,
 ', `coverage`="',
 `coverage`,
 '", `completeness` = ', 
`completeness`,
 ', `confidence` =',
 `confidence`,
 ' WHERE record_id = ',
 `record_id`, 
';') FROM `Assembly_Global_Backup_12Sep2012`.`databases` WHERE `database_name` LIKE "WoRMS%"