TRUNCATE TABLE common_names;
TRUNCATE TABLE `databases`;
TRUNCATE TABLE distribution;
TRUNCATE TABLE families;
TRUNCATE TABLE lifezone;
TRUNCATE TABLE `references`;
TRUNCATE TABLE scientific_name_references;
TRUNCATE TABLE scientific_names; 
TRUNCATE TABLE specialists;