#
gawk -F "|" '{
OFS="\t";
#original_name=$3;
sub(" x "," x_",$3);
$2="wp-"$2;
split($3,sn_arr," ");

sub("x_","x ",$3);
sub("x_","x ",sn_arr[2]);

genus_or_name = "";
infraspecies_marker = "";
infraspecies_epithet = "";
species_epithet = "";
author = "";

if (match($1,/^S$/)) {


for (i=1; i<= length(sn_arr); i++) {
   if (i == 1) { genus_or_name = sn_arr[i];}
   else if (i == 2) { 

species_epithet = sn_arr[i];
if (match(species_epithet,"^x ")) {sub("^x ","",species_epithet); $9="Hybrid taxon. "$9}

}
   else { author = author " " sn_arr[i];}
} 
}
else if (match($1,"SS|V|FM")) {

flag = 0;

for (i=1; i<= length(sn_arr); i++) {
i_next = i + 1;
   if (match(sn_arr[i], "(^ssp|^var|^f)\\.$"))  { 
   if (sn_arr[i_next]!="&amp;") {flag = 1; subsp_index = i;}}
   else {
   if (i == 1) { genus_or_name = sn_arr[i];}
   else if (i == 2) { 
        species_epithet = sn_arr[i];
if (match(species_epithet,"^x ")) {sub("^x ","",species_epithet); $9="Hybrid taxon. "$9;}
}
   }

   if (flag == 1) {
     if (i == subsp_index) { infraspecies_marker = sn_arr[i];}
     else if (i == subsp_index + 1) { infraspecies_epithet = sn_arr[i];}
     else { author = author " " sn_arr[i];}
     } 
   } 
}
else {
genus_or_name = sn_arr[1];
author = "";
for (i=2; i<= length(sn_arr); i++) {author = author " " sn_arr[i];}
}


if(NR==1) {parent_taxon = "Parent"; sp_id = $2;}
else if(NR==2) {parent_taxon = "Top"; sp_id = $2;}
else if($1~"^O$") {parent_taxon = parent_class; sp_id = $2;}
else if($1~"^F$") {parent_taxon = parent_order; sp_id = $2;}
else if($1~"^G$") {parent_taxon = parent_family; sp_id = $2;}
else if ($1~"^S$") {parent_taxon = parent_genus; sp_id = "wp-"NR;}
else if ($1~"^SS$|^V$|^FM$") {parent_taxon = parent_species; sp_id = "wp-s."NR;}
else {parent_taxon = parent_taxon; sp_id = $2;}


if (NR == 1) {print "Taxon	ID	Original name	Genus or name	Species epithet	Infraspecies marker	Infraspecies epithet	Author	Parent	Literature	TrivialName	Distribution	Synonyms	Status	Remarks";}
else if ($1~"^SS$|^V$|^FM$" && species_epithet != previous_species_epithet) {

print "S", 
"wp-"NR,
genus_or_name " " species_epithet,
genus_or_name,
species_epithet,
"",
"",
"",
 parent_genus,
 $4,
 $5,
 $6,
"",
 $8,
"Binomial generated by Sp2000";

parent_species = "wp-"NR;
previous_genus = genus_or_name;
previous_species_epithet = species_epithet;

print $1, 
sp_id,
$3,
genus_or_name,
species_epithet,
infraspecies_marker,
infraspecies_epithet,
author,
 parent_species,
 $4,
 $5,
 $6,
 $7,
 $8,
 $9;

}
else {
 print $1, 
sp_id,
$3,
genus_or_name,
species_epithet,
infraspecies_marker,
infraspecies_epithet,
author,
 parent_taxon,
 $4,
 $5,
 $6,
 $7,
 $8,
 $9;

}

if ($1~"^O$") {parent_order = $2;}
else if($1~"^F$") {parent_family = $2;}
else if($1~"^G$") {parent_genus = $2;}
#else if($1~"G" && NR==2) {parent_class = $2;}
else if ($1~"^S$") {
parent_species = sp_id;
previous_genus = genus_or_name;
previous_species_epithet = species_epithet;
#previous_species_author = author;
}


}' ../in.csv

