<?php
/**
 * Annual Checklist Interface
 *
 * ac.phtml
 * Info - Annual Checklist page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
printf($this->translate('Info_annual_checklist'), $this->app->edition);
?>
</div>
<?php
echo $this->navigator_top;
$fcImgAlt = $this->app->edition . ' Annual Checklist DVD front cover';
?>
<div class="info_content">
<p style="margin-bottom: 20px;">

<span style="width: 325px; float: right; padding-left: 5px; margin-left: 5px; margin-bottom: 15px;"><img
    src="../images/dvd_front_cover.jpg"
    title="2012 Annual Checklist DVD front cover"
    alt="2011 Annual Checklist DVD front cover" width="317"
    height="317" class="bordered-img" /><br />
</span>

This release of the Catalogue of Life contains contributions from <b><?php echo $this->stats['databases']-2; ?></b>
 databases with information on <b><?php echo $this->stats['species']; ?></b>  species, <b><?php echo $this->stats['infraspecific_taxa']; ?></b>
 infraspecific taxa and also includes <b><?php echo $this->stats['synonyms']; ?></b> synonyms and <b><?php echo $this->stats['common_names']; ?></b>
 common names covering the following groups:

<p><b class="field_header">Viruses</b>
 &#8226; <?php
echo $this->internalLink('Viruses and Subviral agents from [link:db:14]');
?>
</p>
<p><b class="field_header">Bacteria</b> and <b class="field_header">Archaea</b> from 
<?php echo $this->internalLink('[link:db:115]'); ?>
</p>
<p><b class="field_header">Chromista</b>
 &#8226; <?php echo $this->internalLink('Chromistan fungi from [link:db:28]');?>
 &#8226; <?php echo $this->internalLink('Foraminifers from [link:db:157]'); ?>
</p>
<p><b class="field_header">Protozoa</b>
 &#8226; <?php echo $this->internalLink('Major groups from [link:db:17]'); ?>
 &#8226; <?php echo $this->internalLink('Ciliates from [link:db:113]'); ?>
 &#8226; <?php echo $this->internalLink('Polycystines from [link:db:109]'); ?>
 &#8226; <?php echo $this->internalLink('Protozoan fungi from [link:db:28] and [link:db:33]'); ?>
 &#8226; <?php echo $this->internalLink('Microsporidians from [link:db:148]'); ?>
 &#8226; <?php echo $this->internalLink('Slime moulds from [link:db:53]'); ?>
</p>
<p><b class="field_header">Fungi</b>
 &#8226; <?php echo $this->internalLink('Various taxa in whole or in part from CABI Bioservices databases ([link:db:28], [link:db:23], [link:db:25], [link:db:97] and [link:db:38]) and from four other databases covering [link:db:36], [link:db:12], [link:db:33], [link:db:98]'); ?> 
 &#8226; <?php echo $this->internalLink('Lichens from [link:db:79]'); ?>
</p>
<p><b class="field_header">Plantae (Plants)</b>
 &#8226; <?php echo $this->internalLink('Mosses from [link:db:19]'); ?>
 &#8226; <?php echo $this->internalLink('Liverworts and hornworts from [link:db:74]'); ?>
 &#8226; <?php echo $this->internalLink('Ferns and fern-allies from [link:db:140]'); ?> 
 &#8226; <?php echo $this->internalLink('Cycads from [link:db:163]'); ?> 
 &#8226; <?php echo $this->internalLink('Conifers from [link:db:45]'); ?>
 &#8226; <?php echo $this->internalLink('4 flowering plant families from [link:db:16], 114 families from [link:db:24] and 274 families from [link:db:141]'); ?>
 &#8226; <?php echo $this->internalLink('Plus individual flowering plant families from [link:db:40], [link:db:73], [link:db:117], [link:db:66], [link:db:72], [link:db:15], [link:db:162], [link:db:43], [link:db:56], [link:db:48], [link:db:64]'); ?>.</p>

<p><b class="field_header">Animalia (Animals)</b>
 &#8226; <?php echo $this->internalLink('Marine groups from [link:db:35], [link:db:115], [link:db:13], [link:db:9], [link:db:155], [link:db:95], [link:db:86], [link:db:57], [link:db:87], [link:db:108], [link:db:81], [link:db:154], [link:db:127], [link:db:132], [link:db:58], [link:db:106], [link:db:122], [link:db:125], [link:db:107], [link:db:112], [link:db:94], [link:db:153], [link:db:105], [link:db:152], [link:db:126], [link:db:88], [link:db:129], [link:db:85], [link:db:131], [link:db:99], [link:db:59], [link:db:149], [link:db:104], [link:db:123], [link:db:90], [link:db:109], [link:db:44], [link:db:124], [link:db:60], [link:db:91], [link:db:150], [link:db:111], [link:db:110], [link:db:92], [link:db:93], [link:db:128], [link:db:100]'); ?>
 &#8226; <?php echo $this->internalLink('Rotifers, mayflies, freshwater  hairworms, planarians, water fleas, aquatic mites and copepods from FADA databases: [link:db:47], [link:db:120], [link:db:119], [link:db:135], [link:db:138], [link:db:139] &amp; [link:db:159]'); ?>
 &#8226; <?php echo $this->internalLink('Entoprocts, water bears from [link:db:115]'); ?>
 &#8226; <?php echo $this->internalLink('Spiders, scorpions, ticks &amp; mites from [link:db:29], [link:db:164], [link:db:115], [link:db:30], [link:db:82] [link:db:80] &amp; Mites GSDs: [link:db:63], [link:db:70], [link:db:69] &amp; [link:db:78]'); ?>
 &#8226; <?php echo $this->internalLink('Diplopods, centipedes, pauropods and symphylans from [link:db:41] &amp; [link:db:42]'); ?>
 &#8226; <?php echo $this->internalLink('Dragonflies and damselflies from [link:db:20] database'); ?>
 &#8226; <?php echo $this->internalLink('Stoneflies from [link:db:65]'); ?>
 &#8226; <?php echo $this->internalLink('Cockroaches from [link:db:51]'); ?>
 &#8226; <?php echo $this->internalLink('Praying mantids from [link:db:62]'); ?>
 &#8226; <?php echo $this->internalLink('Stick and leaf insects from [link:db:50]'); ?>
 &#8226; <?php echo $this->internalLink('Ice crawlers from [link:db:170]'); ?>
 &#8226; <?php echo $this->internalLink('Earwigs from [link:db:158]'); ?>
 &#8226; <?php echo $this->internalLink('Grasshoppers, locusts, katydids and crickets from [link:db:21]'); ?>
 &#8226; <?php echo $this->internalLink('Rock crawlers, gladiators from [link:db:168]'); ?>
 &#8226; <?php echo $this->internalLink('Webspinners from [link:db:89]'); ?>
 &#8226; <?php echo $this->internalLink('Zorapterans from [link:db:167]'); ?>
 &#8226; <?php echo $this->internalLink('Bark & parasitic lices from [link:db:133]'); ?>
 &#8226; <?php echo $this->internalLink('Some groups of true bugs from [link:db:26], [link:db:11], [link:db:52], [link:db:54], [link:db:61], [link:db:76], [link:db:83], [link:db:84], [link:db:156], [link:db:96], [link:db:134], [link:db:142], [link:db:143], [link:db:144] &amp; [link:db:171]'); ?> 
 &#8226; <?php echo $this->internalLink('Twisted-wing parasites from [link:db:103] '); ?>
 &#8226; <?php echo $this->internalLink('Lacewings, antlions, owlflies, fishflies, dobsonflies & snakeflies from [link:db:55]'); ?>
 &#8226; <?php echo $this->internalLink('Some beetle groups from the [link:db:27], [link:db:32], [link:db:39], [link:db:161], [link:db:166], [link:db:146] &amp; [link:db:115]'); ?>
 &#8226; <?php echo $this->internalLink('Fleas from [link:db:22]'); ?>
 &#8226; <?php echo $this->internalLink('Flies, mosquitoes, bots, midges and gnats from [link:db:101], [link:db:5] & [link:db:6]'); ?>
 &#8226; <?php echo $this->internalLink('Butterflies and moths from [link:db:18], [link:db:46], [link:db:31], [link:db:49]'); ?>
 &#8226; <?php echo $this->internalLink('Bees &amp; wasps from [link:db:67], [link:db:68], [link:db:34], [link:db:37], [link:db:118] &amp; [link:db:169]'); ?> 
 &#8226; <?php echo $this->internalLink('Molluscs from [link:db:130], [link:db:136], [link:db:137] &amp; [link:db:1]'); ?> 
 &#8226; <?php echo $this->internalLink('Fishes from [link:db:10]'); ?>
 &#8226; <?php echo $this->internalLink('Reptiles from [link:db:8]'); ?>
 &#8226; <?php echo $this->internalLink('Amphibians, birds and mammals from [link:db:115]'); ?>
</p>
<p><span class="field_header">PLUS</span> additional species from various groups from
<?php echo $this->internalLink('[link:db:17], [link:db:75], [link:db:121] and [link:db:165]'); ?>
</p>
<br />
<p class="field_header">The Catalogue of Life Editors</p>
<p>The Catalogue of Life combines the outputs of the Species 2000 and the ITIS programmes. Assembly and publication of the Catalogue of Life is managed by Yuri Roskov in Champaign, working with colleagues around the world.</p>
<p>&#8226; <b><em>Yuri Roskov</em></b>, Catalogue of Life Executive Editor at 
the Species 2000 Office in Species File Group, Illinois Natural History Survey, 
University of Illinois, Champaign IL, USA.
</p>
<p>&#8226; <b><em>Luisa Abucay</em></b>, Catalogue of Life Database Manager at the CoL Philippines Office, FIN, Los Ba&ntilde;os, Philippines.</p>
<p>&#8226; <b><em>Thomas Orrell</em></b>, ITIS Deputy Director, ITIS Secretariat, Smithsonian Institution, Washington DC, USA.</p>
<p>&#8226; <b><em>David Nicolson</em></b>, ITIS Data Development Leader, USGS, Smithsonian Institution, Washington DC, USA.</p>
<p>&#8226; <b><em>Christina Flann</em></b>, Taxonomic Editorial Advisor for flowering plants at the Species 2000 Secretariat, Naturalis, Leiden, The Netherlands.</p>
<p>&#8226; <b><em>Nicolas Bailly</em></b>, Taxonomic Editorial Advisor for Marine sectors at Hellenic Centre for Marine Research, Heraklion, Crete, Greece.</p> 
<p>&#8226; <b><em>Paul Kirk</em></b>, Taxonomic Editorial Advisor for Fungi and Chromista sectors at the Royal Botanic Gardens, Kew, Richmond, UK.</p>
<p>&#8226; <b><em>Thierry Bourgoin</em></b>, Taxonomic Editorial Advisor for Insects at the Museum National d'Histoire Naturelle, Paris, France.</p>
<p>&#8226; <b><em>Edward DeWalt</em></b>, Taxonomic Editorial Advisor for Aquatic Insects at the Illinois Natural History Survey, University of Illinois, Champaign IL, USA.</p>
<p>&#8226; <b><em>Wim Decock</em></b>, Taxonomic Editorial Advisor for marine taxa (WoRMS) at the Flanders Marine Data Centre, VLIZ, Oostende, Belgium</p>
<p>&#8226; <b><em>Aaike De Wever</em></b>, Taxonomic Editorial Advisor for freshwater taxa (FADA) at the Royal Belgian Institute of Natural Sciences, 
Brussels, Belgium.</p>

<br/>
<p class="field_header">The Catalogue of Life Assembly Team at FIN, Los Ba&ntilde;os, Philippines.</p>
<p>&#8226; <b><em>Luisa Abucay</em></b>, Catalogue of Life Database Manager.</p>
<p>&#8226; <b><em>Jeremiah Jansalin</em></b>, Assistant for Catalogue of Life Database Manager.</p>

<br/>
<p class="field_header">The Catalogue of Life Software Development Team at Naturalis, Leiden, the Netherlands</p>
<p>&#8226; <b><em>Wouter Addink</em></b>, general management.</p>
<p>&#8226; <b><em>Ruud Altenburg</em></b>, software support and development.</p>
<p>&#8226; <b><em>Hugo van Duijn</em></b>, systems administration.</p>
<p>&#8226; DVD project: <b><em>Daphne Duin</em></b> (project manager), <b><em>Maarten Schermer</em></b> (installer for Windows), <b><em>Ruud Altenburg</em></b> (installer for Mac), <b><em>Foppe Pieters</em></b> (installer for Linux), <b><em>Paul Klinkenberg</em></b> (booklet design and DVD production).
</p>

<br/>
<p class="field_header">Photo on the cover:</p>
<p>&#8226; &copy; <b><em>Valter Jacinto</em></b>; Jumping Tree Bug (<i>Calocoris nemoralis</i> forma <i>coccinea</i>), Portugal, Algarve, 30/04/2010.</p>

</div>
<?php echo $this->navigator_bottom; ?>