<?php
/**
 * Annual Checklist Interface
 *
 * cite.phtml
 * Info - How to cite this work page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Cite_work')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">

<p class="field_header">How to cite the Catalogue of Life monthly edition on the Web:</p>
<p>
Roskov Y., Abucay L., Orrell T., Nicolson D., Flann C., Bailly N., Kirk P., Bourgoin T., DeWalt R.E., Decock W., De Wever A., eds. (2016). Species 2000 & ITIS Catalogue of Life, 28th September 2016. Digital resource at www.catalogueoflife.org/col. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-8858.</p>


<p class="field_header">How to cite the Annual Checklist on the web:</p>
<p>
Roskov Y., Abucay L., Orrell T., Nicolson D., Flann C., Bailly N., Kirk P., Bourgoin T., DeWalt R.E., Decock W., De Wever A., eds. (2016). Species 2000 & ITIS Catalogue of Life, 2016 Annual Checklist. Digital resource at www.catalogueoflife.org/annual-checklist/2016. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-884X.</p> 

<p class="field_header">How to cite the Annual Checklist on DVD:</p>
<p>
Roskov Y., Abucay L., Orrell T., Nicolson D., Flann C., Bailly N., Kirk P., Bourgoin T., DeWalt R.E., Decock W., De Wever A., eds. (2016). Species 2000 & ITIS Catalogue of Life, 2016 Annual Checklist. DVD. Species 2000: Naturalis, Leiden, the Netherlands. ISSN 2405-917X.</p> 


<p class="field_header">How to cite individual databases included in this work:</p>

<?php include 'citelist.html'?>
</div>
<?php
echo $this->navigator_bottom;
?>