<?php
/**
 * Annual Checklist Interface
 *
 * contact.phtml
 * Info - Contact page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Contact_us')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>Users of the Catalogue of Life are encouraged to provide feedback to the Species 2000 Secretariat and to ITIS. Enquiries about the Catalogue of Life, contributing databases or Species 2000 orgaisation should also be directed to:</p>
<p>Species 2000 Secretariat<br />
Naturalis Biodiversity Center <br />
P.O. Box 9517, 2300 RA Leiden, Netherlands<br />
</p>
<p>Email: <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a><br />
Tel: +31 71 751 9362 <br />
</p>
<p>Help Desk: <a href="mailto:support@sp2000.org">
support@sp2000.org</a></p>

<p class="field_header">Annual Checklist DVD requests</p>
<p>The Annual Checklist database and software on the DVD are identical to
those on the web at <a href="http://www.catalogueoflife.org/annual-checklist" target="_blank">
http://www.catalogueoflife.org/annual-checklist</a>.
Further copies of the DVD (or the 2017 edition that will be released in
April 2017) can be requested free of charge from Species 2000 Secretariat 
by emailing <a href="mailto:sp2000@sp2000.org">sp2000@sp2000.org</a>.
</p>

</div>
<?php
echo $this->navigator_bottom; ?>