<?php
/**
 * Annual Checklist Interface
 *
 * copyright.phtml
 * Info - Copyright page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Copyright_reproduction_sale')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>&copy; 2016, Species 2000<br />
This online database is copyrighted by Species 2000 on behalf of the
Catalogue of Life partners.</p>
<p>Use of the content (such as the classification, synonymic species checklist, and scientific names) for publications and databases by individuals and organizations for not-for-profit usage is encouraged, on condition that full and precise credit is given at three levels on all occasions that records are shown. The three-part credit includes the complete work, the contributing database of the record, and the expert who provides editorial scrutiny of the taxonomic record. For example, these might be as follows:</p>
<p>
1) <i>Species 2000 &amp; ITIS Catalogue of Life,</i> [please specify exact edition, for example, <i>25th March 2016</i> or <i>2016 Annual Checklist</i>],<br />
2) The full or short name of the contributing database, such as:
<em>World Spider Catalog</em> or <em>WSC</em>,<br />
3) The names of author(s)/editor(s) of the contributing database, such as <em>Kropf C., Nentwig W., Gloor D.</em> (from <i>WSC</i>) or <em>Yunakov N.</em> (from <i>3i Curculio</i>).<br />
</p>
<p>This three-part credit can in many cases be kept brief by using a
standard form and one or more logos as in the following example:
"Species recognized by Maslin B., World Wide Wattle, ver. 2.0 of Dec 2015 in the Catalogue of Life, 2016 Annual Checklist". 
</p>
<p>If you wish to use the content on a public portal or webpage you are
required to notify the Species 2000 Secretariat, both to request written permission and to assist with a check that the correct credits are given.</p>

<p class="field_header">Commercial Use</p>
<p>Use of this compilation or any of the databases contained within it by
 commercial organisations requires a written agreement from Species 2000 and ITIS.
 This applied when it is used commercially for external services, products or
 publications and when it is used to provide internal services within an organisation.
</p>

<p class="field_header">Disclaimer</p>
<p><b></b>The Species 2000 &amp; ITIS Catalogue of Life editorial board
cannot guarantee the accuracy or completeness of the information in this
edition. Be aware that the Catalogue of Life is still
incomplete and undoubtedly contains errors. Neither Species 2000 &amp;
ITIS nor any contributing
database can be made liable for any direct or indirect damage arising out of
the use of Catalogue of Life.</p>

<p>ISSN 2405-8858 (Catalogue of Life monthly editions)</p>
</div>
<?php
echo $this->navigator_bottom;
?>