<?php
/**
 * Annual Checklist Interface
 *
 * websites.phtml
 * Info - Websites page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Web_sites')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p class="field_header">Online version of the Annual Checklist:</p>
<p>
<a href="http://www.catalogueoflife.org/annual-checklist" target="_blank">http://www.catalogueoflife.org/annual-checklist</a>
<!-- <a href="<?php echo $this->app->location; ?>" target="_blank"><?php echo $this->app->location; ?></a> --></p>

<p class="field_header">Latest version of the CoL monthly editions:</p>
<p><a href= "http://www.catalogueoflife.org/col" target="_blank">www.catalogueoflife.org/col</a></p>

<p class="field_header">Archives of the Annual Checklists 2000-2015:</p>
<p><a href= "http://www.catalogueoflife.org/content/annual-checklist-archive" target="_blank">http://www.catalogueoflife.org/content/annual-checklist-archive</a></p>

<p class="field_header">Darwin Core Archives of monthly editions:</p>
<p><a href= "http://www.catalogueoflife.org/DCA_Export/archive.php" target="_blank">http://www.catalogueoflife.org/DCA_Export/archive.php</a></p>

<p class="field_header">Web service:</p>
<p>Species 2000 provides web services to facilitate automated access to
the Annual Checklist by computer programs. Please visit
<a href= "http://www.catalogueoflife.org/content/web-services">http://www.catalogueoflife.org/content/web-services</a> for
more information.</p>

<p class="field_header">CoL Download Service in Darwin Core Archive:</p>
<p><a href= "http://www.catalogueoflife.org/DCA_Export" target="_blank">http://www.catalogueoflife.org/DCA_Export</a></p>

<p class="field_header">CoL website:</p>
<p><a href= "http://www.catalogueoflife.org" target="_blank">www.catalogueoflife.org</a></p>

<p class="field_header">CoL on Facebook:</p>
<p><a href= "http://www.facebook.com/pages/Catalogue-of-Life/102621393156622" target="_blank">www.facebook.com/pages/Catalogue-of-Life/102621393156622</a></p>

<p class="field_header">CoL Twitter:</p>
<p><a href= "https://twitter.com/catalogueoflife" target="_blank">https://twitter.com/catalogueoflife</a></p>

</div>
<?php
echo $this->navigator_bottom;
?>