<?php
/**
 * Annual Checklist Interface
 *
 * copyright.phtml
 * Info - Copyright page view
 *
 * @category    ACI
 * @package     application
 * @subpackage  views/scripts
 *
 */
?>
<div class="page_header">
<?php
echo $this->translate('Copyright_reproduction_sale')?>
</div>
<?php
echo $this->navigator_top;
?>
<div class="info_content">
<p>&copy; 2015, Species 2000<br />
This online database is copyrighted by Species 2000 on behalf of the
Catalogue of Life partners.</p>
<p>Use of the content (such as the classification, synonymic species checklist, and scientific names) for publications and databases by individuals and organizations for not-for-profit usage is encouraged, on condition that full and precise credit is given at three levels on all occasions that records are shown. The three-part credit includes the complete work, the contributing database of the record, and the expert who provides editorial scrutiny of the taxonomic record. For example, these might be as follows:</p>
<p>
1) <i>Species 2000 &amp; ITIS Catalogue of Life,</i> [please specify exact edition, for example, 21st April 2015 or 2015 Annual Checklist],<br />
2) The full or short name of the contributing database, such as:
<em>Dermaptera Species File</em> or <em>DermapteraSF</em>,<br />
3) The names of author(s)/editor(s) of the contributing database, such as <em>Hopkins H., Maehr M.D., Haas F. and Deem L.S.</em> (from DermapteraSF) or <em>Hoeksema B.</em> (from WoRMS Octocorallia).<br />
</p>
<p>This three-part credit can in many cases be kept brief by using a
standard form and one or more logos as in the following example:
"Species recognized by Guilbert E., Lace Bugs Database, ver. 1 of Aug 2013 in the Catalogue of Life: 2015 Annual Checklist". 
</p>
<p>If you wish to use the content on a public portal or webpage you are
required to notify the Species 2000 Secretariat, both to request written permission and to assist with a check that the correct credits are given</p>

<p class="field_header">Commercial Use</p>
<p>Use of this compilation or any of the databases contained within it by
 commercial organisations requires a written agreement from Species 2000 and ITIS.
 This applied when it is used commercially for external services, products or
 publications and when it is used to provide internal services within an organisation.
</p>

<p class="field_header">Disclaimer</p>
<p><b></b>The Species 2000 &amp; ITIS Catalogue of Life editorial board
cannot guarantee the accuracy or completeness of the information in this
edition. Be aware that the Catalogue of Life is still
incomplete and undoubtedly contains errors. Neither Species 2000 &amp;
ITIS nor any contributing
database can be made liable for any direct or indirect damage arising out of
the use of Catalogue of Life.</p>

<p>Copyright for booklet photographs remains with the contributors.</p>
<p>ISSN 2405-8858 (Catalogue of Life, online monthly editions)</p>
</div>
<?php
echo $this->navigator_bottom;
?>